### ISSUE TITLE
Does this fork sitll work?

### ISSUE THREAD

**Issue by Azureki** [Fmstrat/agriget#1]
I am looking for a theme of ttrss which support preview image, but this repo seems to not be maintained for 2 years. Does it still work now? How do you preview image in ttrss?

**Comment by Fmstrat** [comment]
Honestly I should probably update it, but it does still work (for me anyway). However, 99% of my reading is with Palabre on android with my fork of the TTRSS plugin (changes just merged and soon to be released in play store). The changes there add image support, saved articles, and massively speed up processing.

If I have time later this week I will see about doing an update here, too.

**Comment by Azureki** [comment]
Thanks for your reply. I will deploy it when I am free tomorrow.


I prefer to read on web because the screen of phone is small and most rss readers have a limit of synced articles.
